version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/checkout

    steps:
      - checkout

      # Download and cache dependencies (update the numerical cache key suffix manually to force a newer version)
      - restore_cache:
          keys:
            - dependencies-and-browsers-{{ checksum "extension/yarn.lock" }}-{{ checksum "extension/download-bergamot-translator-wasm-artifacts.sh" }}-1

      - run:
          name: Download and import Bergamot Translator build artifacts
          # Note: the import step runs again before building the extensions, which ensures that the latest .appendix.js is used despite cached artifacts
          command: cd extension && yarn bergamot-translator:download-and-import

      - run:
          name: Install dependencies
          command: cd extension && yarn install --frozen-lockfile

      - run:
          name:  Install Firefox
          command: |
            cd extension
            yarn get-firefox:linux
            # Prevent any tests from using the default installed version of Firefox by accident
            sudo rm /usr/bin/firefox || true

      - save_cache:
          paths:
            - extension/downloaded-bergamot-translator-wasm-artifacts
            - extension/node_modules
            - extension/firefox-nightly-linux
          key: dependencies-and-browsers-{{ checksum "extension/yarn.lock" }}-{{ checksum "extension/download-bergamot-translator-wasm-artifacts.sh" }}-1

      - run:
          name: Print which version of Firefox is installed
          command: |
            cd extension
            echo "Version of Firefox installed:"
            ./firefox-nightly-linux/firefox-bin -v

      - run:
          name: Lint
          command: cd extension && yarn lint

      - run:
          name: Import Bergamot Translator build artifacts
          # The import step runs again here to ensure that the latest .appendix.js is used despite cached artifacts
          command: cd extension && yarn bergamot-translator:download-and-import

      - run:
          name: Build Firefox extension - Native UI variant
          command: cd extension && yarn build:native-ui

      - run:
          name: Build Firefox extension
          command: cd extension && yarn build:default

      - run:
          name: Build Chrome extension
          command: cd extension && yarn build:chrome

      - store_artifacts:
          path: "extension/dist"
          destination: "extension/dist"

      - run:
          name: Run tests
          command: cd extension && FIREFOX_BINARY=./firefox-nightly-linux/firefox-bin yarn just-test
